apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
  namespace: kube-system
stringData:
  accessKeyID: minio
  secretAccessKey: minio123
  endpoint: http://192.168.49.2:9000
  #regiom: none for minio
