apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: my-app-container
    image: nginx
    volumeMounts:
    - mountPath: "/data"
      name: my-cstor-volume
  volumes:
  - name: my-cstor-volume
    persistentVolumeClaim:
      claimName: my-cstor-volume-claim

