# Generated by Django 5.0.3 on 2024-03-09 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("role_name", models.CharField(max_length=255)),
                ("last_login", models.DateTimeField()),
                ("active_status", models.SmallIntegerField()),
            ],
            options={"abstract": False,},
        ),
    ]
