# Generated by Django 5.0.3 on 2024-03-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BugLogs",
            fields=[
                ("bug_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("severity", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("reported_date", models.DateField(blank=True, null=True)),
            ],
            options={"db_table": "bug_logs", "managed": False,},
        ),
        migrations.CreateModel(
            name="CodeRepo",
            fields=[
                ("repository_id", models.AutoField(primary_key=True, serialize=False)),
                ("repository_name", models.CharField(max_length=255)),
                (
                    "repository_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_commit_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "code_repo", "managed": False,},
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("position", models.CharField(blank=True, max_length=255, null=True)),
                ("department_id", models.IntegerField()),
                ("salary", models.BigIntegerField(blank=True, null=True)),
            ],
            options={"db_table": "employee", "managed": False,},
        ),
        migrations.CreateModel(
            name="Permissions",
            fields=[
                ("permission_id", models.AutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=255)),
                ("table_name", models.CharField(max_length=255)),
                ("read_access", models.IntegerField()),
                ("write_access", models.IntegerField()),
                ("delete_access", models.IntegerField()),
            ],
            options={"db_table": "permissions", "managed": False,},
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                ("project_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("expected_end_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"db_table": "projects", "managed": False,},
        ),
        migrations.CreateModel(
            name="ProjectTasks",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"db_table": "project_tasks", "managed": False,},
        ),
        migrations.CreateModel(
            name="TestCases",
            fields=[
                ("test_case_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("result", models.TextField()),
            ],
            options={"db_table": "test_cases", "managed": False,},
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("role_name", models.CharField(max_length=255)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("active_status", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "users", "managed": False,},
        ),
        migrations.CreateModel(
            name="Warnings",
            fields=[
                ("warning_id", models.AutoField(primary_key=True, serialize=False)),
                ("query", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"db_table": "warnings", "managed": False,},
        ),
    ]
