# Generated by Django 5.0.3 on 2024-03-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("anomaly_detector", "0004_customuser_delete_user"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RenameModel(old_name="CustomUser", new_name="User",),
    ]
