# Generated by Django 5.0.3 on 2024-03-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anomaly_detector", "0005_rename_customuser_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warning",
            fields=[
                ("warning_id", models.IntegerField(primary_key=True, serialize=False)),
                ("query", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("status", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anomaly_detector.user",
                    ),
                ),
            ],
            options={"db_table": "warnings",},
        ),
    ]
